site_name: Recetario
site_url: https://recetas.tomasocio.es

nav:
  - Inicio: index.md
  - Recetas:
      - Pollo con verduras: Pollo con verduras.md
      - Lasagna: Lasagna.md
      - Garbanzos: garbanzos.md
      - Arroz con leche: arrozleye.md
      - Bechamel: bechamel.md
      - Zarza: zarza.md
      - Tallarines Teriyaki: fideos_teriyaki.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Light mode